lib/src/screens/supa_socials_auth.dart
As environment in pubspec.yaml says, this package uses Dart SDK version 2.17.0 or higher, 
```yaml
environment:
sdk: ">=2.17.0 <3.0.0"
flutter: ">=1.17.0"
```
so use enhanced enum feature is available.
Instead of defining functions like `capitalizeName`, `getIcon`, `getBtnBgColor` inside `_SupaSocialsAuthState` class, this PR includes such properties in `SocialProviders` enum.
=> refactor SocialProviders by using Dart 2.17 enhanced enum

CHANGELOG.md, example/pubspec.lock, lib/src/screens/supa_email_auth.dart, lib/src/screens/supa_magic_auth.dart, lib/src/screens/supa_reset_password.dart, lib/src/screens/supa_send_email.dart, pubspec.yaml
I was trying to use this against the latest flutter dev library and there was a naming conflict on the GoTrue exception class name. They changed it with the version bump that the dev3 version of the supabase flutter library uses compared to the dev1 version that this was originally written against.
=> Update fix GoTrueException naming update from their version bump

example/lib/main.dart, example/lib/phone_sign_in.dart, example/lib/phone_sign_up.dart, example/lib/sign_in.dart, example/lib/sign_up.dart, lib/src/screens/supa_email_auth.dart, lib/src/screens/supa_phone_auth.dart
Draft one - to include both phone sign ups and sign ins. the first only had sign ins and was calling the wrong method on sign up. 
Also, i noticed within the supabase_flutter lib in phone auth sign up - it throws an error if res.data is empty. But res.data would be empty till verification. This blocks the flow coz an error will always be thrown and yet the verification code was being sent to my phone.
=> fix: phone auth

README.md, example/macos/Runner/DebugProfile.entitlements, example/macos/Runner/Release.entitlements, example/pubspec.lock, lib/src/screens/supa_email_auth.dart, lib/src/screens/supa_magic_auth.dart, lib/src/screens/supa_phone_auth.dart, lib/src/screens/supa_reset_password.dart, lib/src/screens/supa_send_email.dart, lib/src/screens/supa_socials_auth.dart, lib/src/screens/supa_verify_phone.dart, lib/src/utils/constants.dart, lib/src/utils/supabase_auth_ui.dart
- Users can decide how to react after the Supabase action finishes :
- Add ```onSuccess``` callback instead of the success alert for most components. 
- Add ```onError``` callback instead of the error alert for most components. 
- For example callbacks are needed in order to display a page asking the user to verify their email when signing up or using a magic link.
- Fix some typos.
- Fix missing ```redirectUrl```.
- Add a ```CircularProgressIndicator```on some buttons.
- Reword some buttons to "Continue" when they both signin and signup. (Magic Link & Providers).
- Call signIn after signUp to handle cases where user already exists (or when email verification isn't set).
=> Support a more elaborated authentication workflow

CHANGELOG.md, pubspec.yaml
I think now that supabase_flutter v1.0.0 is used, we can release v0.0.1 of this library. It is still in v0, so we can still introduce breaking changes if we need to.
=> chore: publish v0.0.1

CHANGELOG.md, lib/src/components/supa_socials_auth.dart, pubspec.yaml
Feature
After using social auth the package shows a SnackBar with no option to not show it.
Added a bool to SupaSocialsAuth to give the developer the choice to have this SnackBar be shown. The bool is optional and the default value is true, causing no change from the current behavior without the developer setting it to false on their own.
Additionally removed an extra space between the word "in" in the SnackBar message and the ! at the end of the String.
=> feat: Make SupaSocialsAuth success SnackBar optional

example/android/build.gradle, pubspec.yaml
(https://github.com/supabase-community/flutter-auth-ui/issues/56)
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
=> Fixes #56 - update supabase_flutter to 2.0.1

README.md, example/lib/sign_in.dart, lib/src/components/supa_socials_auth.dart
This PR removes `SocialProviders` enum and uses `OAuthProvider`, which is the same enum used in supabase_flutter for OAuth sign in and native Google and Apple sign in to have a more aligned API with the main supabase_flutter library. 
```dart
SupaSocialsAuth(
socialProviders: [
SocialProviders.apple,
SocialProviders.google,
],
colored: true,
redirectUrl: kIsWeb
```
```dart
SupaSocialsAuth(
socialProviders: [
OAuthProvider.apple,
OAuthProvider.google,
],
colored: true,
redirectUrl: kIsWeb
```
=> refactor!: Use OAuthProvider instead of SocialProvider to align with supabase_flutter

lib/src/components/supa_socials_auth.dart
- Use [unnamed extension](https://dart.dev/language/extension-methods#unnamed-extensions) only for private.
- Remove unnecessary prefix underscore(`_`) because unnamed extension’s methods and static menbers are only visible within the declaration.
In previous code, the extension getters allows you to access from outside, even though they have an underscore (_) prefix.
```dart
import 'src/components/supa_socials_auth.dart';
OAuthProvider.apple._iconData;
```
=> refactor: Changed OAuthProvider extension to unnamed only for private

lib/src/components/supa_email_auth.dart
Feature: possibility to add "headless" metadata in email signup
The only user metadata that can be added today is through extra text fields
But you can add data using the plain `supabase.auth.signUp(data: ...)` call
One can add extra user metadata information that don't need to be exposed or chosen by the user.
Example: a User type. If I show the signup form is in a "Player" screen, i want to pass `type: "player"` as metadata behind the scenes.
=> Headless signup user metadata option

lib/src/components/supa_socials_auth.dart
Bug fix/Enhancement to SupaSocialsAuth.
Without the `scopes` and ability to include `prompt=consent` in the provider OpenID `/authorize` request, users are never given the opportunity to grant permissions to an app beyond just the ability to sign in.
It is now possible to add scopes and query parameters to `SocialsAuth`.
```
SocialsAuth(
socialProviders: [
SocialProviders.azure,
],
colored: true,
redirectUrl: authService.redirectUrl,
onSuccess: (Session response) {},
onError: (error) {},
scopes: '.default',
queryParams: (promptConsent) ? {'prompt': 'consent'} : {},
)
```
This example triggers a consent prompt for all permissions the Azure app registration has requested. 
https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc#the-default-scope
This is a requirement for apps …
=> Update SupaSocialsAuth to pass scopes and query params to signInWithOAuth

lib/src/components/supa_email_auth.dart, lib/src/components/supa_phone_auth.dart, lib/src/components/supa_reset_password.dart
Make flutter-auth-ui work well with password managers.
Password managers are unable to pick up the password field.
Password managers can pick up the password field.
=> Add autofill hints

lib/src/components/supa_email_auth.dart, lib/src/components/supa_phone_auth.dart
Adds an AutofillGroup to the email sign in form
Fixes #79 
Activating the email field will now propt for autofill data, selecting an entry from the password field will also fill the email field.
=> Fix autofill not opening when tapping on email field in SupaEmailAuth

lib/src/components/supa_email_auth.dart, lib/src/components/supa_phone_auth.dart
This PR introduces [TextInputActions](https://api.flutter.dev/flutter/services/TextInputAction.html) to the email and phone sign-up/-in forms.
#81
A small QoL change in the way that phone keyboards are configured for traversing the forms. The change is the "next" right arrows button in the bottom right of the keyboard.
[with actions.webm](https://github.com/supabase-community/flutter-auth-ui/assets/24683548/af53401f-be44-4ebd-bd48-38e4e57e59a1)
Add any other context or screenshots.
=> Add TextInputAction to phone and email sign in

lib/src/components/supa_email_auth.dart
Bug fix
The E-Mail will use the URL from the configuration inside the Supabase dashboard. However, when using e.g. a sub package which is different from the configured URL, the E-Mail will provide the wrong link and the user can't reset his password.
It will use the redirectTo field as expected.
=> Add redirectTo for email password reset

lib/src/components/supa_email_auth.dart, lib/src/components/supa_reset_password.dart, lib/src/localizations/supa_email_auth_localization.dart, lib/src/localizations/supa_reset_password_localization.dart
FIXES #88 
Password reset flow is incomplete in `SupaEmailAuth`
Successful password reset flow
N/A
=> FIX Password Reset Flow in SupaEmailAuth

lib/src/components/supa_email_auth.dart, lib/src/components/supa_magic_auth.dart, lib/src/components/supa_phone_auth.dart, lib/src/components/supa_reset_password.dart, lib/src/components/supa_socials_auth.dart, lib/src/components/supa_verify_phone.dart, pubspec.yaml
=> Upgrade `sign_in_with_apple` dependency for WASM build support

lib/src/components/supa_socials_auth.dart, lib/src/localizations/supa_socials_auth_localization.dart
Adds a localization feature to override the OAuth provider name
```dart
SupaSocialsAuth(
socialProviders: const [OAuthProvider.azure],
localization: const SupaSocialsAuthLocalization(
oAuthButtonLabels: {
OAuthProvider.azure: 'Continue with Microsoft (Azure)'
},
),
onSuccess: (session) {
// sHandle success
},
),
```
Closes https://github.com/supabase-community/flutter-auth-ui/issues/87
=> feat!: Allow the OAuth provider labels to be overridden on `SupaSocialsAuth`

lib/src/components/supa_email_auth.dart
Adds `onToggleSignIn` and `onToggleRecoverPassword` parameter to `SupaEmailAuth` so that users of `SupaEmailAuth` can observe the internal state of `SupaEmailAuth` and react to it accordingly such as changing the display text on an appBar of the parent widget. 
Fixes https://github.com/supabase-community/flutter-auth-ui/issues/95
=> feat: Add callback for internal state of SupaEmailAuth

lib/src/components/supa_email_auth.dart
Adds a new `resetPasswordRedirectTo` so that users can be redirected to a different URL for password recovery flow.
=> feat: Allow password recovery email to be redirected to other URL

lib/src/components/supa_email_auth.dart, lib/src/components/supa_phone_auth.dart, lib/src/components/supa_socials_auth.dart, pubspec.yaml
This PR adds a feature where if the user tries to sign-up, and the user actually is an anonymous user, this library will automatically upgrade the user to a normal authenticated user instead of calling signUp and creating a new user. 
Fixes https://github.com/supabase-community/flutter-auth-ui/issues/91
=> feat!: Upgrade anonymous users to regular users automatically if opted in

lib/src/components/supa_email_auth.dart
Feature
Currently, the form does not automatically submit when the "Enter" key is pressed. The focus management is also not optimal, and there is no immediate feedback on input validation. The code for button press handlers is also not well organized, affecting readability and maintainability.
1. **Form Submission on Enter Key Press**:
- Added functionality to submit the form automatically when the "Enter" key is pressed, improving user experience.
```dart
onFieldSubmitted: (_) {
if (_isRecoveringPassword) {
_passwordRecovery();
}
}
```
2. **Focus Management**:
- Introduced focus management to ensure the email field is focused if validation fails, guiding the user to the correct input field.
```dart
final FocusNode _emailFocusNode = FocusNode();
...
focusNode: _emailFocusNode,
```
3. …
=> feat: Improve form interaction and code organization in supa_email_auth component

lib/src/components/supa_socials_auth.dart
Adds launch mode parameter so users can decide how to launch their links
Closes #84  
Adds flexibility
=> enhancement: allow user to decide launch mode

lib/src/components/supa_email_auth.dart
Fixes #113, where the values of text fields for MetadataFields on the SupaEmailAuth widget were getting lost, causing them to submit empty strings.
The cause of the issue was how the SupaEmailAuth widget was storing TextEditingControllers for the MetadataFields in the map `_metadataControllers`, with an instance of the MetadataField being used as the key, with a TextEditingController as the value.
Later, in the `build()` method, the list of MetaDataFields were iterated upon, with each accessing its corresponding controller in the map. Unfortunately, at this point the MetadataField would be a separate instance with different hashkeys, so the original TextEditingController stored in the map would not be retrieved.
Flutter handles this failure silently; if a null value is passed to …
=> Fix MetadataFields text field values being lost in SupaEmailAuth widget (Fixes #113)

lib/src/components/supa_email_auth.dart
feature
We always display the login form by default
We added a parameter to control whether sign up for or sign-in form is being displayed initially.
From the business perspective, depending on the UX flow, you should be able to present either login or sign-up. For example, a page with CTA "try for free, no credit card required" should redirect to a sign-up form, not a login form that requires one additional unnecessary step from the user.
https://github.com/supabase-community/flutter-auth-ui/pull/107
=> feat: Support for displaying sign-in or sign-up initially

lib/src/components/supa_email_auth.dart
Add `passwordValidator` parameter to SupaEmailAuth to allow overriding the default validation behavior.
Resolve #118
=> Feature: add custom password validation to SupaEmailAuth form

lib/src/components/supa_email_auth.dart
=> Add value property to BooleanMetaDataField to set initial state of checkbox

lib/src/components/supa_email_auth.dart
- Add autoFormValidation to MetaDataField (fixes #123)
Fixes issue where form could submit with MetaDataField in an invalid state. New behavior matches that of password and email fields.
- Remove hardcoded styling for BooleanMetaDataField to prevent it from overriding an app's ThemeData (fixes #124)
Fixes issue where border outlines would always appear. New behavior leaves styling up to ThemeData. If users of this library request it, we could potentially add these back as parameters for BooleanMetaDataField to pass down to its child CheckboxListTile, but that doesn't seem necessary for now.
=> Add autovalidation and remove hardcoded styling from checkboxes

lib/src/components/supa_email_auth.dart, lib/src/localizations/supa_email_auth_localization.dart
Feature
Currently, the SupaEmailAuth component does not include a field for confirming the password during the sign-up process. This can lead to user errors if they mistype their password without realizing it.
This PR introduces a new feature that adds a "Confirm Password" field to the SupaEmailAuth component, which is only displayed during the sign-up process. This field ensures that users enter their password correctly by requiring them to type it twice. The localization for the "Confirm Password" label and error message has also been added to support multiple languages.
=> Add Confirm Password Field to SupaEmailAuth Component for Sign-Up Process

lib/src/components/supa_email_auth.dart
Feature
The email field is always focused when the form is displayed, which may not be desired in all cases.
Adds an `autofocus` parameter to `SupaEmailAuth` to let developers control whether the email input field should be auto-focused on initial render.
The default value is `true`, maintaining the original behavior unless explicitly changed.
=> Add autofocus option to SupaEmailAuth
